sudo: required
services:
- docker
language: shell
dist: bionic
os: linux
env:
  global:
  - TRAVIS_SECURE_ENV_VARS=true
  - DOCKER_PLATFORMS='linux/arm64'
  - BUILD_ARCH='arm64'
  - DOCKERFILE='Dockerfile'
  - TAGS='latest'
  - secure: W5NlwGqd8zPx0PSpno4QjM/MyNPYUP8/I0LdEcL6allC9ZEdhP4DGPhfCDzh2Iz1MWrZ09sKy4mXmdz2JVVr33hY5/WYCnjvpSYIoy+WWm9+VER4FE5o7WBZf4bDUfraKuxYQpvfcwNKL55NXIiQiruf46xlIRbiV79Sgk1znOUBGvgDCTGO60gaxvMSAIEPF0FHfgdO1M6b2rtH2BvkClzD5TQzZTH6MGaaXmfbz83fhFbS4Ip3KoVFxNSgM3O1DQKdHP6kGNIdTadFc3a4pthxpUAt5dB/D+W2mCU+Kl911e9IKRg1ZWyITFX4X08S/m2FFLZi5gghZgVbmuB+pU1CAlwUkOQellw4bmrpxBApZQpk2jKwhPOVO/kvD9PmMn2VOJZO214hI8iHXi3jJb5ywnCyunsdE9SKcG7LSCxCvyg9pkYczUagYg0GT18SBl3WTH5ayelLL5rH40DanX+9c6PrFQ2PHEhwiOrrsD5oWuIgC2bssCNpLoKJBhC8ALapr0FPfSopTsWw9WJCNUg8SbtH/V2QmU+yhz5hq2oGp1X3lHgvsNQfNUsTtQQp2r5LVAEP22V3qtonWCOGLxAlbDY9GpzZOBGADup6oORLyI72GDOhCggz1mTMQCN6mWiAomx5veg43tQr4UZFJWAYfvVljPjavh3Rm/i31jg=
  - secure: MXsZpdOPRdIw6buTjPheoEQZ8y5isMa3FK1/rL2RbFyIYJxm4BqyaI8ni0gBNq+jn4vZZ6Y6bYeXoR1lZqEtpnA/o791LmsGzuoEgxvxK+00ogLCDafOAmVYghfCdHfTBzKEp50dxtj1ww3Nsv6m3HaV0TxN81tKKLzyfCYe6qvKkmt+X5hfm6NxUhutEWIdosH8gl9l3Cmg+BsTUssjeoL0rLP7yewpM3hEqLodVEgfsLtCm74g7yf+GagWxHnYU+WFaSqQSFWlooweCKfG60xrVmxsZAk7mjS1hdJGqdK7Ab//0JXS/WIgrlk6i9ytRlDDb8jFQgbJtZTfxSaryN0V+mxI2ySt8OrfCUOExWokyrMn6Wsleg/t1CjFBayiyr3i9EXln6wjs7AfajLbL1BMfEzsAp23kYEBVOx8o1LeJ5f92EyvOOrgC22sxXRx2rKy+Ya+c7LEdSmZTeDQzsyzoGK9rxYqzK5cRQoZJGeJOgDm7w+wuwZA/xL64HxUPDuDgv/wg14Qg0UsUuLwl6o/WIVZgIToVJA9NSOSuFCMpVevZRU2lLBejJ5lbBe/dHHU/qXAtgtLw8T40NnRLlW+mqQLabgQjnnqlHgmXZW+QbNtrb4MbPK8XJBHLN+x6uE69sNGG8kGX8flYQkmy5e1atrNlKiceHaQse9s6P4=
  - secure: MMZep5EASszPSYb43ailzhK5wnydOrSK9OZVVwGzY5h5oKHpvFyY+t9TCEkXrpkex3F2cxgj+mEfuGxBhdbLIhcBuc8o+NoeoM5GQhVyjRE+DOwI0Z/OuYQ+/bzQfUojgrM5AzAwmxmpt/AkvxjPflREWIKqRUNQCAH9uTAAIS5Uo4Eg6wHLUTrbrds5MhFTsxEKragH63Z6vADPbl1IAYHp/Dy+B+3tIWgx1uQN2r4muv8tDka5e+aqFxTQE28zovYMkRgx3bhJ2P8PuhVTaMoFnlPq5MecNvO/bshRe4ImMiQKPs3GKY91B7CH2HhO8F9DiUvW35dGg5zUbFks7fYfOkbqYI8ASDbDV9HsKQ21taDRVpFMOL96HeCC1OWnug97qSDuDYb0GaT2frFIkMxY+q1/lf0ur4qjo/sx3GU3Wg0T72jcv9/oJSqDsGzoUYbzH8x9mJ6VrggK0BJLlAz+ZUiBpdmRb3VKgBnf7jKTs4UdbHJF2LvbyLr9iRMmU6S4mIP1OVTGBLn/DNyd5TKTGiaTseiSdUxSmVLN4LZJRv+lmag54t8JPxYiyysG7fjRGWOGv8e8rGsi3cPmBlkt9ibZWghoC+vtBxgn2j74CBY1t6AP9SwVyuS5fdVkdziw7k8pfVzyx2yCZPPqNC47ZbxGNkkaJq5EKGvKXaM=
install:
- source ./build-images-ci.sh
- set -ex; buildx_images_ci::setup_environment; set +x
defaults:
  script: &1
  - DOCKER_BASE=${TRAVIS_REPO_SLUG}'-arm64'
  - source ./build-images-ci.sh
  - set -ex; buildx_images_ci::build_and_push_image; set +x
jobs:
  fast_finish: true
  include:
  - stage: build
    env:
    - DOCKER_PLATFORMS='linux/arm64'
    - TAGS='arm64'
    script: *1
after_success:
- source ./build-images-ci.sh
- set -ex; buildx_images_ci::create_push_manifest; set +x
